name = "sarvamsai"
compatibility_date = "2026-04-24"
compatibility_flags = ["nodejs_compat"]

pages_build_output_dir = "."

[[d1_databases]]
binding = "DB"
database_name = "sarvamsai-db"
database_id = "YOUR_D1_ID"
